config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :movies do
    member do
      post 'like' => 'movies#upvote'
    end
    resources :comments do
      member do
        post 'like' => 'comments#upvote'
        post 'dislike' => 'comments#downvote'
      end
    end
  end
   root 'movies#index'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :movies
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
	 acts_as_votable
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  director    :string
#  category_id :integer
#  length      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Movie < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "325x475>", thumb: "250x350>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :title, presence: true
	validates :description, presence: true
	validates :length, numericality: {only_integer: true, less_than_or_equal_to: 999 }, presence: true
  belongs_to :category
	belongs_to :user
	has_many :comments

	acts_as_votable
	
	extend FriendlyId
	friendly_id :title, use: [:slugged, :history]

	 def should_generate_new_friendly_id
	 	title_changed?
	 end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
  has_many :movies
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_movie
	before_action :find_comment, except: [:new,:create]

	def new
		@comment = @movie.comments.new
	end

	def create
		@comment = @movie.comments.create(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to movie_path(@movie)
		end
	end

	def edit
		
	end

	def update
		if @comment.update(comment_params)
			flash[:success] = "Updated your comment successfully"
			redirect_to movie_path(@movie)
		end
	end

	def destroy
		@comment.destroy
		flash[:notice] = "Already deleted your comment!"
		redirect_to movie_path(@movie)
	end

	def upvote	
		@comment.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@comment.downvote_by current_user
		redirect_to :back
	end

	private

	def find_movie
		@movie = Movie.friendly.find(params[:movie_id])
	end

	def find_comment
		@comment = @movie.comments.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:comment, :rating)
	end
end

app/controllers/movies_controller.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  director    :string
#  category_id :integer
#  length      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class MoviesController < ApplicationController
	before_action :find_movie, except: [:index, :new, :create]
	before_action :authenticate_user!, except: [:index]

	def index
		if params[:category].blank?
					@movies = Movie.all.order("created_at DESC")
				else
					@category_id = Category.find_by(name: params[:category]).id
					@movies = Movie.where(category_id: @category_id).order("created_at DESC")
				end
	end

	def show
		@comments = @movie.comments.all
		if @comments.blank?
			@avg_rating = 0
		else
			@avg_rating = @comments.average(:rating).round(2)
		end
		set_page_title @movie.title
	end

	def new
		@movie = current_user.movies.build
	end

	def create
		@movie = current_user.movies.build(movie_params)
		if @movie.save
			redirect_to @movie
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @movie.update(movie_params)
			redirect_to @movie
		else
			render :edit
		end
	end

	def destroy
		@movie.destroy
		redirect_to root_path
	end

	def upvote
		@movie.upvote_by current_user
		redirect_to :back
	end

	private

	def find_movie
		@movie = Movie.friendly.find(params[:id])
	end

	def movie_params
		params.require(:movie).permit(:title, :description, :director, :category_id, :length, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

 def youtube(content)
    context = { gfm: true}
    pipeline = HTML::Pipeline.new [
  HTML::Pipeline::YoutubeFilter,
  HTML::Pipeline::MarkdownFilter
  ], context

  pipeline.call(content)[:output].to_s.html_safe
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  director    :string
#  category_id :integer
#  length      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module MoviesHelper

	def render_avg_rating(movie)
		movie.comments.average(:rating)
  end
end

app/views/comments/_comment.html.erb
<div class="comments">
	
	<% @comments.each do |comment| %>
		<div class="comment_body">
			<%= simple_format(comment.comment) %>
			<div class="star-rating pull-right" data-score= <%= comment.rating %> > </div>
		</div>
		<div class="comment_info">	
				<p class="user">Posted by <em><%= comment.user.email %></em></p>
				<p class="time"><em><%= time_ago_in_words(comment.created_at) %> Ago</em></p>
		</div>

		
		<div class="btn-group">
			<% if current_user = comment.user %>
				<%= link_to edit_movie_comment_path(@movie, comment), class: "btn btn-default btn-xs" do %>
					<i class="fa fa-pencil"></i>
				<% end %> 
				<%= link_to movie_comment_path(@movie, comment), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn-xs" do  %>
					<i class="fa fa-trash-o"></i>
				<% end %>
			<% end %>
			<%= link_to like_movie_comment_path(@movie,comment), class: "btn btn-default btn-xs", method: :post do  %>
				<i class="fa fa-thumbs-o-up"></i> <%= comment.get_upvotes.size %>
			<% end %>
			<%= link_to dislike_movie_comment_path(@movie,comment), class: "btn btn-default btn-xs", method: :post do  %>
				<i class="fa fa-thumbs-o-down"> <%= comment.get_downvotes.size %></i>
			<% end %>
		</div>
		<hr>
	<% end %>

</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/comments/_form.html.erb
<%= simple_form_for [@movie, @movie.comments.build] do |f| %>
 <div class="field">
    <div id="star-rating"></div>
  </div>
	<%= f.input :comment, label: "Write your review below and give out star rating!" %>
	<%= f.submit class: "btn btn-success" %>
<% end %>
<hr>


<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'comment[rating]'
  });
</script>

app/views/comments/edit.html.erb
<h2>Edit your Comment</h2>

<%= simple_form_for [@movie, @comment] do |f| %>
	<div class="field">
    <div id="star-rating"></div>
  </div> <br>
	<%= f.input :comment, label: "Edit your review below!" %>
	<%= f.submit class: "btn btn-success" %>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'comment[rating]'
  });
</script>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <a class="navbar-brand" href="/">Hot Movies</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="new_movie"><%= link_to "New Movie", new_movie_path  %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span>Select Types</span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li><%= link_to "All Movies", root_path  %></li>
            <% Category.all.each do |category| %>
              <li>
                <%= link_to category.name, movies_path(category: category.name)  %>
              </li>
            <% end %>
          </ul>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Sign Up", new_user_registration_path  %></li>
          <li> <%= link_to("Sign In", new_user_session_path) %> </li>
        <% else %>
          <li><%= link_to "Account", edit_user_registration_path  %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<%= render 'common/navbar' %>
	<%= notice_message %>
		
	<%= yield %>
	</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
	<div class="category">	
	<%= f.collection_select :category_id, Category.all, :id, :name, { promt: "Choose a Category" } %>
	</div>
	<div class="title">
		<%= f.input :title %>
	</div>
	<div class="description">
		<%= f.input :description %>
	</div>
	<div class="director">
		<%= f.input :director %>
	</div>
	<div class="length">
		<%= f.input :length, label: "Length(min)" %>
	</div>
	<div class="image_file">
		<%= f.input :image, as: :file %>
	</div>

	<%= f.submit class: "btn btn-danger" %> 

<% end %>

app/views/movies/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading" id= "head">
				<h1>Edit Your Movie</h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to "Back", movie_path(@movie)  %>
			</div>
		</div>
	</div>
</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Add Your Favorite Movies Information or Reviews</h1>
    <p>Sign up for 100% free! Come on!</p>
    <p><%= link_to "Sign Up Now", new_user_registration_path, class: "btn"  %></p>
  </div>
<% end %>
<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-md-3 col-sm-3">
			<div class="pull-left panel panel-default" id="box">
				<div class="image_wrapper">
	        <%= link_to (image_tag movie.image.url(:thumb), class: "movie_img"), movie %>
				</div>
        <h3><%= link_to movie.title, movie  %></h3>
				<div class="panel-footer clearfix">
					<div class="icon">
						<span><i class="fa fa-comment"></i> <%= movie.comments.size %></span>
						<span><i class="fa fa-heart"> <%= movie.get_upvotes.size %></i>
						</span>
					</div>
					<div class="star-rating" data-score= <%= render_avg_rating(movie) %> ></div>
				</div>
			</div>
		</div>
		
	<% end %>
</div>


<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
   v
</script>

app/views/movies/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading" id= "head">
				<h1>Add New Movie</h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
			<div class="panel-footer">
				<%= link_to "Back", root_path  %>
			</div>
		</div>
	</div>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<%= image_tag(@movie.image.url(:medium), class: "thumbnail") %>
				<div class="table-responsive">
					<table class="table table-bordered">
						<tbody>
							<tr>
								<td><strong>Title:</strong></td>
								<td><%= @movie.title %></td>
							</tr>
							<tr>
								<td><strong>Director:</strong></td>
								<td><%= @movie.director %></td>
							</tr>
							<tr>
								<td><strong>Length:</strong></td>
								<td><%= @movie.length %> min</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="col-md-8 movie_info">
				<% if @movie.user = current_user %>			
					<div class="btn-group pull-right" role="group">
						<%= link_to edit_movie_path(@movie), class: "btn btn-default" do %>
						<i class="fa fa-pencil"></i>
						<% end %>
						<%= link_to like_movie_path(@movie), class: "btn btn-default", method: :post do  %>
							<i class="fa fa-heart"> <%= @movie.get_upvotes.size %></i>
						<% end %>
					</div>
				<% end %>
			<h2>
			<%= @movie.title %></h2>
			<div class="star-rating" data-score= <%= @avg_rating %> ></div>
			<h6>Posted by <%= @movie.user.email %></h6>
			<p><%= youtube(@movie.description) %></p>
			</div>
		</div>
	</div>
	<div class="panel-footer">
		<%= render 'comments/form' %> <br>
		<%= render 'comments/comment' %>
	</div>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>